[package]
name = "OpenGLMinecraft"
version = "0.1.0"
authors = ["lukec"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.20.0"
gl = "0.12.0"
png = "*"
rand = "*"
noise = "0.5.1"